#! /bin/sh
# Copyright (c) 2025 D. Bohdan
# License: MIT
# Requires git(1) for configuration, rsync(1), and sha256sum(1).
set -eu

config_file=${XDG_CONFIG_HOME:-$HOME/.config}/up/config
host=$(git config --file "$config_file" up.host)
dest_dir=$(git config --file "$config_file" up.dir)
url=$(git config --file "$config_file" up.url)

exit_code=0
random=$(dd if=/dev/random count=1 2>/dev/null | sha256sum | cut -c -2)
subdir=$(printf '%x%s' "$(date +%s)" "$random")

for file in "$@"; do
    if ! [ -f "$file" ]; then
        echo 'up: cannot access file:' "$file" >&2
        exit_code=1
        continue
    fi

    if rsync --checksum --mkpath --progress --times "$file" "$host":"$dest_dir"/"$subdir"/"$file"; then
        echo "${url%/}/$subdir/$file"
    fi
done

exit "$exit_code"
