#! /bin/sh
# Copyright (c) 2025 D. Bohdan
# License: MIT
# Requires git(1) for configuration and rsync(1).
set -eu

me=$(basename "$0")
config_file=${XDG_CONFIG_HOME:-$HOME/.config}/up/config

if ! [ -f "$config_file" ]; then
    printf '%s: config file not found at %s\n' "$me" "$config_file" >&2
    exit 1
fi
host=$(git config --file "$config_file" up.host)
dest_dir=$(git config --file "$config_file" up.dir)
url=$(git config --file "$config_file" up.url)

exit_code=0
subdir=$(printf '%x' "$(date +%s)")

for file in "$@"; do
    if ! [ -f "$file" ]; then
        printf '%s: bad file: %s\n' "$me" "$file" >&2
        exit_code=1
        continue
    fi

    basename=$(basename "$file")

    if rsync \
        --checksum \
        --mkpath \
        --progress \
        --times \
        "$file" \
        "$host":"$dest_dir"/"$subdir"/"$basename"; then
        echo "${url%/}/$subdir/$basename"
    fi
done

exit "$exit_code"
